/**
 * Safe, injectable entry point for one isolated Oracle volume-group restore
 * drill. It reads only explicit private JSON inputs and never invents
 * acceptance evidence: acceptance and accepted-state cleanup require a
 * separate typed acceptance receipt supplied by the operator, and the create
 * stage stops at a durable CREATED result. The exceptions are the
 * receipt-free abort cleanups: an exact CREATED drill whose durable lifetime
 * already elapsed before acceptance, and an exact partial create journal that
 * reached one or more reconciled CREATED resources but never a durable result
 * because isolation proof or the clone launch failed. Every input path and
 * every persisted path must be a relative path rooted exactly at `.private`
 * without traversal segments, and only the journal and result are persisted
 * under that directory. The default invocation fails closed unless the exact
 * action and every required input are present.
 *
 * The OCI runner, its credentials and the cloud mutations stay in the
 * injected deps: this module holds no credentials and no production IDs.
 * The create action additionally binds a complete private Pi/helper
 * copied-volume preparation runtime configuration, and the production wrapper
 * wires the real preparation adapter into the pre-boot isolation gate only
 * when that full configuration validates against the reviewed plan; otherwise
 * create fails closed before any provider mutation.
 */
import { withBackupLock } from "./backup-lock.ts";
import {
  assertOracleMutationAllowed,
  readGate,
} from "./backblaze-controller-gate.ts";
import {
  abortPartialGroupRestoreExecution,
  acceptGroupRestoreExecution,
  cleanupGroupRestoreExecution,
  executeGroupRestoreCreates,
  type GroupRestoreAcceptanceReceipt,
  type GroupRestoreExecutionInput,
  type GroupRestoreExecutionPorts,
  type GroupRestoreExecutionResult,
  type GroupRestorePartialCleanupResult,
  type GroupRestorePreBootIsolationAdapter,
  ociGroupRestorePorts,
  prepareGroupRestoreExecution,
} from "./oci-group-restore-executor.ts";
import {
  type GroupRestoreApproval,
  type GroupRestoreEvidence,
  type GroupRestoreJournal,
  type GroupRestoreLifetime,
  groupRestoreLifetime,
  type GroupRestorePlan,
  type GroupRestoreRunner,
  validateGroupRestoreApproval,
} from "./oci-group-restore-drill.ts";
import {
  groupRestorePreparationAdapter,
  groupRestorePreparationBundle,
  type GroupRestorePreparationConfig,
  validateGroupRestorePreparationConfig,
} from "./oci-group-restore-preparation.ts";
import { defaultRunner, readPrivateJson, writePrivateJson } from "./oci.ts";

export type GroupRestoreRunAction = "create" | "accept" | "cleanup";

export interface GroupRestoreRunInputs {
  /** Reviewed plan JSON (GroupRestorePlan). */
  planPath: string;
  /** Reviewed approval JSON (GroupRestoreApproval). */
  approvalPath: string;
  /** Live group-capture metadata JSON (GroupRestoreEvidence). */
  evidencePath: string;
  /** Complete private Pi/helper copied-volume preparation runtime config
   * (GroupRestorePreparationConfig); required for create, never for accept or
   * cleanup. */
  preparationPath?: string;
  /** Operator-supplied typed acceptance receipt JSON; required for accept and
   * cleanup, never generated by this tool. */
  acceptancePath?: string;
}

export interface GroupRestoreRunConfig {
  action: GroupRestoreRunAction;
  /** Durable `.private` directory for the lifetime, journal and result. */
  privateDir: string;
  inputs: GroupRestoreRunInputs;
}

/** Injected IO and cloud surface so the cycle is testable without files or
 * credentials. */
export interface GroupRestoreRunDeps {
  now: () => Date;
  readJson: <T>(path: string) => Promise<T>;
  writeJson: (path: string, value: unknown) => Promise<void>;
  runner: GroupRestoreRunner;
  makePorts: (
    plan: GroupRestorePlan,
    lifetime: GroupRestoreLifetime,
  ) => GroupRestoreExecutionPorts;
  /** True only when the caller's ports carry a real pre-boot isolation
   * verifier: the OCI gate proves the reviewed isolated network and exact
   * restored targets AND a typed copied-volume preparation adapter
   * (`GroupRestorePreBootIsolationAdapter`) is configured for the duplicate-
   * job masking hook. The create action refuses before any input/state read
   * or provider call while this is false: launching the restored clone
   * without the preparation hook would let an unprepared or duplicate-job
   * guest boot beside production. */
  preBootIsolationReady: boolean;
}

export const GROUP_RESTORE_STATE_FILES = {
  lifetime: "group-restore-lifetime.json",
  journal: "group-restore-journal.json",
  result: "group-restore-result.json",
} as const;

function assertBound(value: string, label: string): string {
  if (
    value === undefined || value === "" || value.includes("<") ||
    value.includes("OCID>") || value.includes("$")
  ) {
    throw new Error(`${label} is not bound`);
  }
  return value;
}

/** Only a path rooted at `.private` may carry JSON inputs or drill state: the
 * path must be relative, start with exactly `.private` and contain no `.`,
 * `..`, empty or absolute/backslash segment, so traversal or absolute-path
 * escapes are impossible. */
function assertPrivatePath(path: string, label: string): string {
  assertBound(path, label);
  const segments = path.split("/");
  if (
    path.startsWith("/") || path.includes("\\") || segments[0] !== ".private" ||
    segments.some((segment) =>
      segment === "" || segment === "." || segment === ".."
    )
  ) {
    throw new Error(
      `${label} must be a relative path under .private without traversal`,
    );
  }
  return path;
}

function statePath(privateDir: string, name: string): string {
  return `${privateDir}/${name}`;
}

async function requireJson<T>(
  path: string,
  label: string,
  read: GroupRestoreRunDeps["readJson"],
): Promise<T> {
  try {
    return await read<T>(path);
  } catch (error) {
    throw new Error(`${label} is missing or unreadable: ${String(error)}`);
  }
}

async function readOptionalJson<T>(
  path: string,
  read: GroupRestoreRunDeps["readJson"],
): Promise<T | undefined> {
  try {
    return await read<T>(path);
  } catch (error) {
    // Only genuine absence is optional. A durable file that exists but is
    // malformed, unreadable or inaccessible must fail closed: treating it as
    // absent would let a resumed create overwrite the surviving durable
    // record and issue provider mutations against unknown prior state.
    if (error instanceof Deno.errors.NotFound) return undefined;
    throw error;
  }
}

function receiptsEqual(
  left: GroupRestoreAcceptanceReceipt,
  right: GroupRestoreAcceptanceReceipt,
): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

function sameJournal(
  left: GroupRestoreJournal,
  right: GroupRestoreJournal,
): boolean {
  return JSON.stringify(left) === JSON.stringify(right);
}

/** Run one bounded drill action. Pure orchestration over injected IO and
 * ports; every ambiguity, placeholder or missing input fails closed. */
export async function runGroupRestoreCycle(
  config: GroupRestoreRunConfig,
  deps: GroupRestoreRunDeps,
): Promise<GroupRestoreExecutionResult | GroupRestorePartialCleanupResult> {
  if (!["create", "accept", "cleanup"].includes(config.action)) {
    throw new Error("Unknown drill action; the wrapper fails closed");
  }
  // Before ANY input/state read or provider call: a create without a
  // configured pre-boot isolation verifier must never launch the restored
  // clone (the executor hook is the only guard that prepares isolation and
  // masks duplicate jobs before the first boot). This is an intentional
  // safety refusal; the verifier hook itself is never weakened.
  if (config.action === "create" && !deps.preBootIsolationReady) {
    throw new Error(
      "Drill create is refused: this executable requires a configured pre-boot isolation verifier",
    );
  }
  const privateDir = assertPrivatePath(config.privateDir, "State directory");
  for (
    const [label, path] of [
      ["Plan input", config.inputs.planPath],
      ["Approval input", config.inputs.approvalPath],
      ["Evidence input", config.inputs.evidencePath],
    ] as const
  ) {
    assertPrivatePath(path, label);
  }
  if (
    config.action === "accept" &&
    (config.inputs.acceptancePath === undefined ||
      config.inputs.acceptancePath === "")
  ) {
    throw new Error(
      "Acceptance requires an operator-supplied receipt file (accept)",
    );
  }
  if (config.inputs.acceptancePath !== undefined) {
    assertPrivatePath(config.inputs.acceptancePath, "Acceptance receipt input");
  }
  const plan = await requireJson<GroupRestorePlan>(
    config.inputs.planPath,
    "Plan input",
    deps.readJson,
  );
  const approval = await requireJson<GroupRestoreApproval>(
    config.inputs.approvalPath,
    "Approval input",
    deps.readJson,
  );
  const evidence = await requireJson<GroupRestoreEvidence>(
    config.inputs.evidencePath,
    "Evidence input",
    deps.readJson,
  );

  const lifetimePath = statePath(
    privateDir,
    GROUP_RESTORE_STATE_FILES.lifetime,
  );
  const journalPath = statePath(privateDir, GROUP_RESTORE_STATE_FILES.journal);
  const resultPath = statePath(privateDir, GROUP_RESTORE_STATE_FILES.result);
  const persistedResult = await readOptionalJson<GroupRestoreExecutionResult>(
    resultPath,
    deps.readJson,
  );
  const persistedLifetime = await readOptionalJson<GroupRestoreLifetime>(
    lifetimePath,
    deps.readJson,
  );
  const persistedJournal = await readOptionalJson<GroupRestoreJournal>(
    journalPath,
    deps.readJson,
  );
  // Take the run clock after all input/state reads so approval and lifetime
  // checks are not based on a stale timestamp from a slow filesystem read.
  const now = deps.now();

  if (config.action === "create") {
    if (persistedResult !== undefined) {
      throw new Error(
        `Drill already holds a durable ${persistedResult.state} result`,
      );
    }
    const journal = persistedJournal ?? [];
    let lifetime: GroupRestoreLifetime;
    let fresh = false;
    if (persistedLifetime !== undefined) {
      lifetime = persistedLifetime;
      if (groupRestoreLifetimeHasElapsed(lifetime, now)) {
        throw new Error("Durably recorded drill lifetime has already elapsed");
      }
    } else {
      if (journal.length !== 0) {
        throw new Error(
          "Durable drill lifetime is missing for a resumed create",
        );
      }
      lifetime = groupRestoreLifetime(now, plan);
      fresh = true;
    }
    const input: GroupRestoreExecutionInput = {
      plan,
      approval,
      evidence,
      journal,
      now,
      lifetime,
    };
    await prepareGroupRestoreExecution(input, deps.runner);
    // Persist the lifetime only after validation and before the first provider
    // mutation, so a failed input set does not burn the window.
    if (fresh) {
      await deps.writeJson(lifetimePath, lifetime);
    }
    const result = await executeGroupRestoreCreates(
      input,
      deps.runner,
      deps.makePorts(plan, lifetime),
      (nextJournal) => deps.writeJson(journalPath, nextJournal),
    );
    await deps.writeJson(journalPath, result.journal);
    await deps.writeJson(resultPath, result);
    return result;
  }

  if (
    config.action === "cleanup" && persistedResult === undefined
  ) {
    // Receipt-free abort of an exact partial create journal. The create stage
    // writes no result until all three resources exist, so an isolation-proof
    // or clone-launch failure can leave a durable journal with one or more
    // exact CREATED identities and no result. The executor validates plan,
    // evidence, runner and journal identities, refuses before the durable
    // deadline, and deletes only the journaled resources in dependency order;
    // every delete intent stays durable before its provider call and
    // production is proved again after deletion. The CLEANED result keeps
    // restoreDrillProved false, carries no acceptance and reports
    // deadlineExceeded true.
    if (persistedLifetime === undefined) {
      throw new Error("Durable drill lifetime is missing before cleanup");
    }
    if (persistedJournal === undefined) {
      throw new Error("Durable drill journal is missing before cleanup");
    }
    const cleaned = await abortPartialGroupRestoreExecution(
      plan,
      evidence,
      deps.runner,
      deps.makePorts(plan, persistedLifetime),
      persistedLifetime,
      persistedJournal,
      now,
      (nextJournal) => deps.writeJson(journalPath, nextJournal),
    );
    await deps.writeJson(journalPath, cleaned.journal);
    await deps.writeJson(resultPath, cleaned);
    return cleaned;
  }

  if (
    persistedResult === undefined || persistedResult.lifetime === undefined ||
    persistedLifetime === undefined
  ) {
    throw new Error("Durable drill result is missing before acceptance");
  }
  if (
    JSON.stringify(persistedLifetime) !==
      JSON.stringify(persistedResult.lifetime)
  ) {
    throw new Error("Persisted lifetime differs from the durable drill result");
  }
  if (persistedJournal === undefined) {
    throw new Error("Durable drill journal is missing before acceptance");
  }
  if (config.action === "accept") {
    const receipt = await requireJson<GroupRestoreAcceptanceReceipt>(
      config.inputs.acceptancePath!,
      "Acceptance receipt input",
      deps.readJson,
    );
    if (persistedResult.state !== "CREATED") {
      throw new Error(
        `Durable drill result is ${persistedResult.state}, not CREATED`,
      );
    }
    if (!sameJournal(persistedJournal, persistedResult.journal)) {
      throw new Error(
        "Persisted journal differs from the durable drill result",
      );
    }
    await validateGroupRestoreApproval(plan, approval, now);
    const accepted = await acceptGroupRestoreExecution(
      persistedResult,
      plan,
      now,
      receipt,
    );
    await deps.writeJson(resultPath, accepted);
    return accepted;
  }
  if (
    persistedResult.state !== "RESTORE_DRILL_PROVED" ||
    persistedResult.restoreDrillProved !== true ||
    !persistedResult.acceptance
  ) {
    // Receipt-free abort: the executor accepts only an exact unaccepted
    // CREATED result whose durable lifetime already elapsed and refuses an
    // unaccepted cleanup before the deadline. Any other result preserves the
    // existing operator receipt and accepted-state requirement.
    if (persistedResult.state !== "CREATED") {
      if (config.inputs.acceptancePath === undefined) {
        throw new Error(
          "Cleanup requires an operator-supplied acceptance receipt",
        );
      }
      throw new Error(
        "Cleanup requires the durable explicit acceptance state",
      );
    }
  } else {
    if (config.inputs.acceptancePath === undefined) {
      throw new Error(
        "Cleanup requires an operator-supplied acceptance receipt",
      );
    }
    const receipt = await requireJson<GroupRestoreAcceptanceReceipt>(
      config.inputs.acceptancePath!,
      "Acceptance receipt input",
      deps.readJson,
    );
    if (!receiptsEqual(receipt, persistedResult.acceptance)) {
      throw new Error(
        "Operator acceptance receipt differs from the durable acceptance",
      );
    }
  }
  // A cleanup intent is durably published before its provider delete. After a
  // crash, the journal may therefore be ahead of the last result snapshot;
  // resume from that journal while retaining the accepted result metadata.
  const cleanupResult = { ...persistedResult, journal: persistedJournal };
  const cleaned = await cleanupGroupRestoreExecution(
    cleanupResult,
    plan,
    approval,
    evidence,
    deps.runner,
    deps.makePorts(plan, persistedResult.lifetime),
    now,
    (nextJournal) => deps.writeJson(journalPath, nextJournal),
  );
  await deps.writeJson(journalPath, cleaned.journal);
  await deps.writeJson(resultPath, cleaned);
  return cleaned;
}

function groupRestoreLifetimeHasElapsed(
  lifetime: GroupRestoreLifetime,
  now: Date,
): boolean {
  return now.getTime() >= Date.parse(lifetime.deadlineAtUtc);
}

export interface GroupRestoreRunCli {
  config: GroupRestoreRunConfig;
  runnerPath: string;
}

const GROUP_RESTORE_RUN_FLAGS = new Set([
  "--action",
  "--state-dir",
  "--plan",
  "--approval",
  "--evidence",
  "--acceptance",
  "--preparation",
  "--runner",
]);

export function parseGroupRestoreRunArgs(args: string[]): GroupRestoreRunCli {
  const flags = new Map<string, string>();
  for (let index = 0; index < args.length; index += 2) {
    const name = args[index];
    const value = args[index + 1];
    if (name === undefined || !name.startsWith("--") || value === undefined) {
      throw new Error("Invalid drill entry-point arguments");
    }
    if (!GROUP_RESTORE_RUN_FLAGS.has(name) || flags.has(name)) {
      throw new Error(`Unknown or duplicate drill entry-point flag: ${name}`);
    }
    flags.set(name, value);
  }
  const action = flags.get("--action");
  if (
    action === undefined || !["create", "accept", "cleanup"].includes(action)
  ) {
    throw new Error(
      "A bound --action (create|accept|cleanup) is required; the entry point fails closed",
    );
  }
  if (action === "create" && !flags.has("--preparation")) {
    throw new Error(
      "A bound --preparation private configuration path is required for create; the entry point fails closed",
    );
  }
  return {
    config: {
      action: action as GroupRestoreRunAction,
      privateDir: assertPrivatePath(
        flags.get("--state-dir") ?? "",
        "State directory",
      ),
      inputs: {
        planPath: assertPrivatePath(flags.get("--plan") ?? "", "--plan"),
        approvalPath: assertPrivatePath(
          flags.get("--approval") ?? "",
          "--approval",
        ),
        evidencePath: assertPrivatePath(
          flags.get("--evidence") ?? "",
          "--evidence",
        ),
        preparationPath: flags.has("--preparation")
          ? assertPrivatePath(flags.get("--preparation")!, "--preparation")
          : undefined,
        acceptancePath: flags.has("--acceptance")
          ? assertPrivatePath(flags.get("--acceptance")!, "--acceptance")
          : undefined,
      },
    },
    runnerPath: assertPrivatePath(flags.get("--runner") ?? "", "--runner"),
  };
}

/** Same shared controller lock used by every other Oracle-mutating entry
 * point. */
export const GROUP_RESTORE_CONTROLLER_LOCK_PATH =
  ".private/backup-controller.lock";

/** Injectable lock/gate surface for the executable wrapper, so the shared
 * ordering can be proved deterministically without file or cloud state. */
export interface GroupRestoreRunGateDeps {
  lock: <T>(path: string, work: () => Promise<T>) => Promise<T>;
  gate: () => Promise<unknown>;
}

/** Shared executable gate: hold the controller lock for the COMPLETE action
 * invocation (all durable state reads and writes) and immediately check the
 * Backblaze controller gate before anything else runs. A valid active or
 * orphaned gate blocks every Oracle mutation; malformed gate state fails
 * closed. The pure cycle keeps no lock and stays deterministic. */
export async function withGroupRestoreControllerGate<T>(
  work: () => Promise<T>,
  gate: GroupRestoreRunGateDeps = {
    lock: withBackupLock,
    gate: () => readGate(),
  },
): Promise<T> {
  return await gate.lock(GROUP_RESTORE_CONTROLLER_LOCK_PATH, async () => {
    // Immediately inside the shared lock, before any input/state read,
    // runner config or provider call.
    assertOracleMutationAllowed(await gate.gate());
    return await work();
  });
}

async function main(): Promise<void> {
  const { config, runnerPath } = parseGroupRestoreRunArgs(Deno.args);
  await withGroupRestoreControllerGate(async () => {
    const runnerConfig = await readPrivateJson<GroupRestoreRunner>(runnerPath);
    if (
      !runnerConfig.ociCliPath || !runnerConfig.ociProfile ||
      !runnerConfig.region
    ) {
      throw new Error(
        "Runner config must bind ociCliPath, ociProfile and region",
      );
    }
    const runner: GroupRestoreRunner = {
      ociCliPath: runnerConfig.ociCliPath,
      ociProfile: runnerConfig.ociProfile,
      region: runnerConfig.region,
      run: defaultRunner,
    };
    // A create is wired to the real Pi/helper copied-volume preparation
    // adapter ONLY when a complete, explicitly bound private runtime
    // configuration is present and binds the reviewed plan; missing, malformed
    // or mismatching configuration fails closed before any provider mutation
    // (the state machine's own gate still refuses a create without the typed
    // adapter). The hook is never replaced by a readiness flag, mock success
    // or a read-only network check.
    let preparation: GroupRestorePreBootIsolationAdapter | undefined;
    let preBootIsolationReady = false;
    if (config.action === "create") {
      const reviewedPlan = await readPrivateJson<GroupRestorePlan>(
        config.inputs.planPath,
      );
      const preparationConfig = await readPrivateJson<
        GroupRestorePreparationConfig
      >(config.inputs.preparationPath!);
      await validateGroupRestorePreparationConfig(
        preparationConfig,
        reviewedPlan,
        await groupRestorePreparationBundle(reviewedPlan),
      );
      preparation = groupRestorePreparationAdapter(
        preparationConfig,
        reviewedPlan,
        runner,
        { ssh: defaultRunner },
      );
      preBootIsolationReady = true;
    }
    const result = await runGroupRestoreCycle(config, {
      now: () => new Date(),
      readJson: readPrivateJson,
      writeJson: writePrivateJson,
      runner,
      makePorts: (plan, lifetime) =>
        ociGroupRestorePorts(plan, runner, {
          lifetime,
          preBootIsolation: preparation,
        }),
      preBootIsolationReady,
    });
    console.log(JSON.stringify(result, null, 2));
  });
}

if (import.meta.main) {
  await main();
}
